name: Generate documentation
on:
  push:
    paths:
    - 'documentation-generator/**'
    - redirect.json

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Run generator
        run: documentation-generator/run.py
